/** Public, low-volume discovery observations for TEST-018; never a release gate. */
export const googleCanaryCorpus = [
  "Bun WebView documentation",
  "Model Context Protocol specification",
  "Web standard AbortController documentation",
  "TypeScript strict mode handbook",
  "SQLite WAL documentation",
  "RFC 9110 HTTP semantics",
  "MDN URL API",
  "W3C Web Content Accessibility Guidelines",
  "OWASP SSRF prevention cheat sheet",
  "GitHub Actions workflow syntax",
  "Bun test documentation",
  "ECMAScript modules specification",
  "WHATWG Fetch standard",
  "Unicode normalization forms",
  "RFC 3986 URI generic syntax",
  "JSON Lines format",
  "Apache 2.0 license text",
  "Creative Commons Attribution ShareAlike 4.0",
  "NIST TREC COVID qrels",
  "BEIR information retrieval benchmark",
  "SciFact dataset",
  "BM25 ranking function",
  "TREC evaluation NDCG",
  "robots exclusion protocol RFC 9309",
  "Content Security Policy MDN",
  "HTTP 429 Too Many Requests RFC",
  "Google Search Central documentation",
  "OpenAI Model Context Protocol server",
  "Bun SQLite documentation",
  "Web Crypto API MDN",
  "HTML Living Standard",
  "CVE program vulnerability disclosure",
] as const;
